repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: check-ast
    -   id: debug-statements
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: '23.7.0'
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
    -   id: isort
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
-   repo: https://github.com/PyCQA/flake8
    rev: '6.1.0'
    hooks:
    -   id: flake8
repos:
-   repo: https://github.com/python-poetry/poetry
    rev: '1.6.1'
    hooks:
    -   id: poetry-check
    -   id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]